// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  inputs: string;
  placehold: string;
  pokemons: string;
  root: string;
  search: string;
  titleSearch: string;
}
export const cssExports: CssExports;
export default cssExports;
